### PR TITLE
adding setup.py

### LINKED ISSUE #2: Create setup script
A setup.py have to be added to the project.

### PR DESCRIPTION
**Pull request by saadmanrafat**
fixes #2

### CODE REVIEW

**Comment by saadmanrafat** [comment]
yeah should have included a commit message. I will try to refactor the code and add it here very soon.

**Comment by andreiboyanov** [comment]
> yeah should have included a commit message. I will try to refactor the code and add it here very soon.

I just cherry-picked your commit from the master. I'm going to do some more tests later today. The thing with the local imports in the main script should be fixed I think but let me test it again.

**Comment by saadmanrafat** [comment]
I made one change in the setup.py file. I should be working now.

**Comment by andreiboyanov** [comment]
> I made one change in the setup.py file. I should be working now.

I just wanted to ask you to add this entry point. :) Can you just rename the entry point to aftsearch of aftquery ?

I added a test in tests/integrations that shows how exactly the script is not working now. I agree it's a great think to have it as entry point ones the package installed but I want to be able to execute it from the sources also, like in the test:

`python aftsearch.py --help`

**Comment by saadmanrafat** [comment]
okay so I removed the relative imports from the aftsearch.py. The test seems to be working now.

**Comment by andreiboyanov** [comment]
thank you! I'll try to merge later when I'm back home

**Pull request merged**
